version: '2'

services:
  app:
    extends:
      file: ./docker/compose/supply.yml
      service: deps
    environment:
      NODE_ENV: development
    ports:
      - 3999:2999
    command: yarn run start
